# appconfig.toml

# Activalo solo cuando la aplicación esté en modo de desarrollo.
# Esto controla el despliegue de varias funciones y métodos que Fluvel
# implementa PARA EL PROGRAMADOR para facilitar el desarrollo de la app.
DEV_MODE = false # ¡IMPORTANT!

# Configuración general de la aplicación
[app]
app_name = "Fluvel Framework"
version = "1.0.0"
log_level = "INFO" # Nivel de registro: DEBUG, INFO, WARNING, ERROR, CRITICAL
theme = "bootstrap"
language = "es"

# Configuración del tamaño de la ventana principal
[window_size]
width = 600
height = 500

# Configuración de la base de datos (ejemplo, no se recomienda para credenciales sensibles)
[database]
host = "localhost"
port = 5432
user = "admin"
password = "secure_password" # ¡Considera usar variables de entorno para esto en producción!

# Otras configuraciones que podrías añadir
[features]
enable_dark_mode_toggle = true
show_welcome_message = true

[paths]
# Rutas relativas a la raíz del proyecto para recursos específicos
# Aunque 'utils/paths.py' manejará la lógica, puedes definir valores aquí si es necesario
default_icon = "fluvel_icon.svg"