# Main menu sections
[File]
  # New options
  [File.New]
  new_file = "New File"
  new_window = "New Window"
  new_from_template = "New from Template"

  # Open options
  [File.Open]
  open_file = "Open..."
  open_recent = "Open Recent"

  # Close options
  [File.Close]
  close_current = "Close"
  close_all = "Close All"

  # Save options
  [File.Save]
  save = "Save"
  save_as = "Save As..."
  save_all = "Save All"

  # Revert options (for version control/autosave)
  [File.RevertTo]
  browse_all_versions = "Browse All Versions..."

  # Print options
  [File.Print]
  print_dialog = "Print..."
  page_setup = "Page Setup..."
  print_preview = "Print Preview"

  # Import/Export/Share
  import = "Import..."
  export = "Export..."
  export_as = "Export As..."
  share = "Share..."

  # Application exit
  quit = "Quit"

[Edit]
  undo = "Undo"
  redo = "Redo"
  cut = "Cut"
  copy = "Copy"
  paste = "Paste"
  paste_special = "Paste Special..."
  delete = "Delete"
  select_all = "Select All"
  deselect = "Deselect"

  # Find options
  [Edit.Find]
  find = "Find..."
  find_next = "Find Next"
  find_previous = "Find Previous"
  replace = "Replace..."

  # Spelling and Grammar (for text-based apps)
  [Edit.SpellingAndGrammar]
  check_document = "Check Document"
  check_while_typing = "Check Spelling While Typing"

[View]
  zoom_in = "Zoom In"
  zoom_out = "Zoom Out"
  actual_size = "Actual Size"
  fit_to_window = "Fit to Window"
  full_screen = "Full Screen"

  # Show/Hide toggles
  [View.ShowHide]
  toolbar = "Toolbar"
  sidebar = "Sidebar"
  rulers = "Rulers"
  grid = "Grid"
  status_bar = "Status Bar"

  # Layout options
  [View.Layout]
  single_pane = "Single Pane"
  two_panes = "Two Panes"
  three_panes = "Three Panes"

  # Sort By options
  [View.SortBy]
  sort_by_name = "Name"
  sort_by_date_modified = "Date Modified"
  sort_by_size = "Size"

[Window]
  minimize = "Minimize"
  zoom_maximize = "Zoom/Maximize"
  bring_all_to_front = "Bring All to Front"
  arrange = "Arrange"
  # List of open windows would typically be dynamically generated by the application

[Settings]
  preferences = "Preferences..."
  themes = "Themes"
  language = "Language"

[Help]
  help_docs = "Help"
  keyboard_shortcuts = "Keyboard Shortcuts"
  tutorials = "Tutorials"
  support = "Support"
  licence = "Licence"

  # More help options
  [Help.More]
  version = "Version"
  web_page = "Visit us"
  check_for_updates = "Check for Updates"
  about_app = "About Fluvel"