[File]
new_file = "New File"
open = "Open"
save = "Save"
save_us = "Save Us"
quit = "Quit"

[Settings]
preferences = "Preferences"
export = "Export"
export_as = "Export as"


[Help]
licence = "Licence" # getattr(GlobalConfig, licence)

[Help.more]
version = "Version" # getattr(GlobalConfig, version)
web_page = "Visit us" # getattr(GlobalConfig, web_page)
