[fluvel]
DEV_MODE = true

[app]
name = "Fluvel Framework"
version = "0.1.0"
author = "Robotid"
homepage = "https://www.example.com"
licence = "MIT"
copyright = "© 2025 Robotid"

[ui]
theme = "bootstrap"
language = "en"

[window]
title = "FluvelApp"