[fluvel]
DEV_MODE = true

[app]
name = "Fluvel Framework"
version = "0.1.0"
author = "Robotid"
homepage = "https://www.fluvel.com"
licence = "MIT"
copyright = "© 2025 Robotid"

[ui]
theme = "custom"
language = "es"

[window]
width = 720  
height = 500
min_width = 800
min_height = 600
resizable = true
title_bar_hidden = false
icon = "static/icons/app_icon.png"
