import click, re

class ClickStyledMessage:
    """
    A utility class for printing messages to the console using the 
    :func:`click.echo` function and applying foreground color styles 
    using simple markup syntax.

    The markup syntax uses the pattern ``:color_name[text]``, 
    where ``color_name`` is a color supported by Click.

    :cvar regex: The compiled regular expression used to find 
                 and replace the style pattern in the message.
    :vartype regex: str
    """

    regex = r":([a-z_]+)\[(.*?)\]"

    @classmethod
    def _style_replacer(cls, match: re.Match) -> str:
        """
        Replacement function used by :func:`re.sub` to apply 
        the Click style to the matching text.

        :param match: The regular expression match object.
        :type match: re.Match
        :returns: The styled string generated by :func:`click.style`.
        :rtype: str
        """
        fg_color = match.group(1)
        text_content = match.group(2)
        
        return click.style(text=text_content, fg=fg_color)

    @classmethod
    def echo(cls, message: str) -> None:
        """
        Prints a message and a new line to standard output or a file, 
        applying Click styles for the foreground colors defined 
        in the message using the syntax ``:color_name[text]``.

        The supported color names are the same as those in :func:`click.style`:

        * ``black`` (might be a gray)
        * ``red``
        * ``green``
        * ``yellow`` (might be an orange)
        * ``blue``
        * ``magenta``
        * ``cyan``
        * ``white`` (might be light gray)
        * ``bright_black``
        * ``bright_red``
        * ``bright_green``
        * ``bright_yellow``
        * ``bright_blue``
        * ``bright_magenta``
        * ``bright_cyan``
        * ``bright_white``
        * ``reset`` (only resets the color code)

        :param message: The message to print, potentially containing style markers.
        :type message: str
        :returns: Nothing (prints directly to standard output).
        :rtype: None

        Example
        -------
        .. code-block:: python

            ClickStyledMessage.echo(“This is normal, :red[this is red] and :green[this is green].”)
        """

        full_message = re.sub(cls.regex, cls._style_replacer, message)
    
        click.echo(full_message)